Repository atlp-rwanda/dynamites-ecomm-fe, pull requests merged in 2024-06, with the labels that each got.

#7 Project Initialization with Vite (Local & Remote)
  .eslintrc.cjs
  .gitignore
  .prettierrc.cjs
  README.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/icon.png
  src/App.tsx
  src/__test__/App.test.tsx
  src/__test__/setupTests.ts
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: Front-End, Ready for TTL Review

#13 #10 Dockerize the project
  .dockerignore
  Dockerfile
  vite.config.ts
Labels: Front-End

#15 #14 Write project readme file
  README.md
Labels: Front-End

#11 Configure TypeScript Paths
  src/main.tsx
  tsconfig.json
  vite.config.ts
Labels: Front-End, ready for review

#19 Configure dotenv
  .env.example
  .gitignore
  package-lock.json
  package.json
  vite.config.ts
Labels: Front-End, Ready for TTL Review

#12 Set Up Pre-commit Hooks for Linting and Code Formatting
  .github/workflows/application.yml
  .husky/pre-commit
  README.md
  package-lock.json
  package.json
  tsconfig.json
Labels: Front-End, WIP, Ready for TTL Review

#20 organed Folder structure
  package-lock.json
  src/assets/image
  src/components/button
  src/pages/home
  src/services/apiService
  src/stories/story
  src/style/style
  src/utils/utilities
Labels: Ready for TTL Review

#38 set up routes using react router dom
  package-lock.json
  package.json
  src/App.tsx
  src/__test__/App.test.tsx
  src/layout/HomeLayout.tsx
  src/pages/ErrorPage.tsx
  src/pages/Home.tsx
  src/pages/home
  src/routes/AppRoutes.tsx
Labels: Front-End, Ready for TTL Review

#40 Setup redux
  package-lock.json
  package.json
  src/app/hooks.ts
  src/app/store.ts
  src/main.tsx
Labels: Front-End

#43 ft: Fix Add Font
  src/index.css
Labels: bug

#44 Feat: Implement navbar component #21
  package-lock.json
  package.json
  public/avatar.jpg
  public/cart.png
  public/down.png
  public/edit.png
  public/hamburger.png
  public/heart.png
  public/help.png
  public/logo.png
  public/moon.png
  public/settings.png
  public/signout.png
  public/user.png
  src/__test__/navbar.test.tsx
  src/components/Navbar.tsx
  src/layout/HomeLayout.tsx
  tailwind.config.js
Labels: Front-End, Ready for TTL Review

#47 Dynamite Hello section
  .hintrc
  package-lock.json
  package.json
  src/__test__/App.test.tsx
  src/__test__/Hellosection.test.tsx
  src/assets/welcome.jpg
  src/assets/welcome1.png
  src/assets/welcome2.png
  src/components/HelloSection/HelloSection.tsx
  src/components/form/HSButton.tsx
  src/pages/Home.tsx
  tailwind.config.js
  tsconfig.json
Labels: Ready for TTL Review

#50 Implementation of signup page with Redux and Api intengration
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/__test__/Auth_Tests/signUp.test.tsx
  src/__test__/appRouter.test.tsx
  src/app/store.ts
  src/components/form/HSButton.tsx
  src/features/Auth/SignUpSlice.ts
  src/pages/SignUp.tsx
  src/routes/AppRoutes.tsx
Labels: Front-End, WIP, Ready for TTL Review

#24 Implement User Login Feature with Redux Toolkit
  .eslintrc.cjs
  .github/workflows/application.yml
  package-lock.json
  package.json
  src/__test__/signInSlice.test.tsx
  src/app/store.ts
  src/components/button
  src/components/form/Button.tsx
  src/components/form/HSInput.tsx
  src/features/Auth/SignInSlice.ts
  src/index.css
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/routes/AppRoutes.tsx
  tsconfig.json
Labels: Front-End, ready for review

#39 landing page banner section
  .env.example
  .github/workflows/application.yml
  package-lock.json
  package.json
  src/__test__/App.test.tsx
  src/__test__/bannerAds/bannerAds.test.tsx
  src/__test__/bannerAds/bannerSlice.test.tsx
  src/app/bannerAds/BannerSlice.tsx
  src/app/store.ts
  src/assets/egg.png
  src/assets/snacks.png
  src/components/bannerAds/bannerAds.tsx
  src/components/bannerAds/bannerSection.tsx
  src/interfaces/Vendor.ts
  src/interfaces/category.ts
  src/interfaces/product.ts
  src/pages/Home.tsx
  tailwind.config.js
Labels: Front-End, ready for review
