Repository atlp-rwanda/dynamites-ecomm-fe, pull requests merged in 2024-07, with the labels that each got.

#54 Fix: Navbar
  src/__test__/navbar.test.tsx
  src/__test__/signInSlice.test.tsx
  src/components/Navbar.tsx
  src/features/Auth/SignInSlice.ts
Labels: Ready for TTL Review

#64 Integrates the "Most Popular" section on the landing page
  src/__test__/popular/MostPopular.test.tsx
  src/__test__/popular/MostRecent.test.tsx
  src/__test__/popular/MostSelling.test.tsx
  src/__test__/popular/PopularBanner.test.tsx
  src/__test__/popular/PopularItem.test.tsx
  src/__test__/popular/PopularSlice.test.tsx
  src/__test__/popular/PopularTitle.test.tsx
  src/app/store.ts
  src/assets/Image/Rectangle 901.svg
  src/assets/icons/Left-Arrow.svg
  src/assets/icons/Right-Arrow.svg
  src/assets/image
  src/components/Popular/BannerAD.tsx
  src/components/Popular/Item.tsx
  src/components/Popular/MostPopular.tsx
  src/components/Popular/MostRecent.tsx
  src/components/Popular/MostSelling.tsx
  src/components/Popular/PopilarTitle.tsx
  src/components/Popular/Popular_section.tsx
  src/features/Popular/availableProductSlice.ts
  src/pages/Home.tsx
  tailwind.config.js
Labels: Front-End, Ready for TTL Review

#71 Footer Implementation
  package-lock.json
  package.json
  src/__test__/footer.test.tsx
  src/app/Footer/Subscribe.ts
  src/app/store.ts
  src/components/Footer/Footer.tsx
  src/layout/HomeLayout.tsx
  src/utils/ToastConfig.ts
Labels: Front-End, Ready for TTL Review

#69 Feat:Integrate google auth
  src/features/Auth/SignInSlice.ts
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: Ready for TTL Review

#58 Implement 2FA verification
  .eslintrc.cjs
  package-lock.json
  src/App.tsx
  src/__test__/Auth_Tests/signInSlice.test.tsx
  src/__test__/Auth_Tests/twoFactorAuth.test.tsx
  src/__test__/navbar.test.tsx
  src/assets/otp.png
  src/components/HelloSection/HelloSection.tsx
  src/components/form/HSInput.tsx
  src/components/home/ProductCard.tsx
  src/features/Auth/SignInSlice.ts
  src/layout/HomeLayout.tsx
  src/pages/SignIn.tsx
  src/pages/TwoFactorAuthForm.tsx
  src/routes/AppRoutes.tsx
Labels: Front-End, ready for review

#74 Feat: Integrate auth with facebook
  src/features/Auth/SignUpSlice.ts
  src/pages/SignUp.tsx
Labels: Ready for TTL Review, ready for review

#75 side bar implementation
  package-lock.json
  package.json
  src/__test__/dashBoard/dashBoardSideBar.test.tsx
  src/components/dashBoard/DashboardSideNav.tsx
  src/layout/DashbordLayout.tsx
  src/routes/AppRoutes.tsx
Labels: Front-End, ready for review

#79 Implementation of Admin dashboard nav bar
  src/__test__/dashBoard/dashBoardNavBar.test.tsx
  src/__test__/dashBoard/dashBoardSideBar.test.tsx
  src/components/dashBoard/DashboardSideNav.tsx
  src/components/dashBoard/dashBoardNav.tsx
  src/layout/DashbordLayout.tsx
  src/pages/AdminRoutes.tsx
  src/pages/SignIn.tsx
  src/routes/AppRoutes.tsx
Labels: Front-End, Ready for TTL Review

#85 added Admin Dashboard Home
  src/__test__/dashBoard/dashboardHome.test.tsx
  src/app/Dashboard/buyerSlice.ts
  src/app/Dashboard/orderSlice.ts
  src/app/store.ts
  src/assets/AddPeople.svg
  src/assets/DiscIcon.svg
  src/assets/ExportIcon.svg
  src/assets/OrderIcon.svg
  src/assets/SalesIcon.svg
  src/assets/farmer.svg
  src/assets/farmerMarket.png
  src/components/dashBoard/HomeDash.tsx
  src/layout/DashbordLayout.tsx
  src/layout/HomeLayout.tsx
  src/pages/Admin.tsx
  src/routes/AppRoutes.tsx
  src/utils/ToastConfig.ts
  tailwind.config.js
Labels: Front-End, Ready for TTL Review

#87 fix bannerSection
  src/__test__/bannerAds/bannerSlice.test.tsx
  src/app/bannerAds/BannerSlice.tsx
  src/components/bannerAds/bannerAds.tsx
  src/components/bannerAds/bannerSection.tsx
  src/pages/Home.tsx
Labels: bug, Ready for TTL Review

#84 Feat: Implement visitor insights chart and top categories table
  package-lock.json
  package.json
  src/__test__/dashBoard/dashboardHome.test.tsx
  src/components/Chart.tsx
  src/components/TopCategories.tsx
  src/components/dashBoard/HomeDash.tsx
Labels: Ready for TTL Review

#92 Fix image and routing
  public/icons/AddPeople.svg
  public/icons/DiscIcon.svg
  public/icons/ExportIcon.svg
  public/icons/OrderIcon.svg
  public/icons/SalesIcon.svg
  public/icons/farmer.svg
  src/app/Dashboard/buyerSlice.ts
  src/components/dashBoard/HomeDash.tsx
  src/layout/DashbordLayout.tsx
  src/layout/HomeLayout.tsx
  src/pages/SignIn.tsx
  src/pages/TwoFactorAuthForm.tsx
Labels: bug, Front-End, Ready for TTL Review

#45 Feat: Landing page Featured and Best Seller section Implementation
  netlify.toml
  src/__test__/home/ProductGridFour.test.tsx
  src/__test__/home/SectionHeaderCta.test.tsx
  src/__test__/home/productCard.test.tsx
  src/__test__/home/productList.test.tsx
  src/app/store.ts
  src/components/home/BestSellerSection.tsx
  src/components/home/FeaturedSection.tsx
  src/components/home/ProductGridFour.tsx
  src/components/home/SectionHeaderCta.tsx
  src/features/Popular/bestSellingProductSlice.ts
  src/features/Products/ProductSlice.ts
  src/pages/Home.tsx
  src/types/Product.ts
Labels: Front-End, Ready for TTL Review

#95 Feat: Implement shop page
  package-lock.json
  package.json
  public/dollar.png
  src/__test__/shop.test.tsx
  src/components/form/HSInput.tsx
  src/components/home/ProductSkeleton.tsx
  src/features/Products/ProductSlice.ts
  src/index.css
  src/pages/Shop.tsx
  src/routes/AppRoutes.tsx
  tailwind.config.js
Labels: Front-End, ready for review

#99 Fix: Inconsistent product cards
  src/__test__/home/ProductGridFour.test.tsx
  src/__test__/home/productCard.test.tsx
  src/__test__/home/productList.test.tsx
  src/__test__/shop.test.tsx
  src/components/home/ProductCard.tsx
Labels: Ready for TTL Review

#83 implement sales map chart component
  package-lock.json
  package.json
  src/components/dashBoard/HomeDash.tsx
  src/components/salesMap/SalesMap.tsx
  src/features/SaleByCountry/SaleByCountrySlice.ts
  src/layout/DashbordLayout.tsx
Labels: Front-End, ready for review

#88 Orders feature in dashboard
  package-lock.json
  package.json
  public/iphone.svg
  public/product.svg
  src/__test__/Orders/Orders.test.tsx
  src/app/store.ts
  src/components/Cart/Cart.tsx
  src/components/Cart/CartItem.tsx
  src/components/Orders/EditableOrder.tsx
  src/components/Orders/ElipsisIcon.tsx
  src/components/Orders/FilterBar.tsx
  src/components/Orders/NavigationIcon.tsx
  src/components/Orders/OrderDetailsModal.tsx
  src/components/Orders/Orders.tsx
  src/components/Orders/Pagination.tsx
  src/components/Orders/Table.tsx
  src/features/Orders/ordersSlice.ts
  src/features/Products/categorySlice.ts
  src/interfaces/order.ts
  src/pages/Orders.tsx
  src/routes/AppRoutes.tsx
  tsconfig.json
Labels: Front-End, ready for review

#94 Implementing Display Products in the Dashboard
  .eslintrc.cjs
  src/__test__/dashBoard/ConfirmationCard.test.tsx
  src/__test__/dashBoard/NavigateonPage.test.tsx
  src/__test__/dashBoard/dashboardProductSlice.test.tsx
  src/app/store.ts
  src/components/Popular/MostSelling.tsx
  src/components/dashBoard/ConfirmationCard.tsx
  src/components/dashBoard/DashboardSideNav.tsx
  src/components/dashBoard/EditProduct.tsx
  src/components/dashBoard/NavigateonPage.tsx
  src/components/dashBoard/Table.tsx
  src/features/Dashboard/dashboardProductsSlice.ts
  src/pages/AdminRoutes.tsx
  src/pages/DesplayProductPage.tsx
  src/pages/EditPage.tsx
  src/routes/AppRoutes.tsx
  src/utils/UploadImages.ts
Labels: Front-End, Ready for TTL Review

#67 Implement "Add Product" Functionality in Vendor Dashboard
  .hintrc
  package-lock.json
  package.json
  src/__test__/dashBoard/addProductByVendor.test.tsx
  src/__test__/dashBoard/addProductSlice.test.tsx
  src/__test__/dashBoard/cloudinary.test.tsx
  src/app/store.ts
  src/assets/Check.png
  src/assets/threebar.png
  src/components/Orders/EditableOrder.tsx
  src/components/dashBoard/DashboardSideNav.tsx
  src/components/dashBoard/EditProduct.tsx
  src/components/dashBoard/Table.tsx
  src/components/dashBoard/addProducts.tsx
  src/components/form/HSInput.tsx
  src/features/Dashboard/addProductSlice.tsx
  src/pages/SignIn.tsx
  src/pages/TwoFactorAuthForm.tsx
  src/routes/AppRoutes.tsx
  src/utils/cloudinary.tsx
Labels: Front-End, Ready for TTL Review

#108 Feat: Product details page
  src/__test__/categoriesSection.test.tsx
  src/__test__/home/categories.test.tsx
  src/__test__/home/productList.test.tsx
  src/__test__/productDetails.test.tsx
  src/__test__/wishlist.test.tsx
  src/components/ProtectedRoute.tsx
  src/components/WishlistCard.tsx
  src/components/home/ProductCard.tsx
  src/features/Products/ProductSlice.ts
  src/pages/ProductDetails.tsx
  src/routes/AppRoutes.tsx
  tailwind.config.js
Labels: Ready for TTL Review

#112 implemented add to cart and cart
  package-lock.json
  package.json
  public/mastercard.svg
  public/visa.svg
  src/__test__/Cart/Cart.test.tsx
  src/app/store.ts
  src/components/Cart/Cart.tsx
  src/components/Cart/CartItem.tsx
  src/components/home/ProductCard.tsx
  src/features/Cart/cartSlice.tsx
  src/interfaces/cart.ts
  src/routes/AppRoutes.tsx
  tsconfig.json
Labels: Front-End, Ready for TTL Review, ready for review

#110 added Seller Dashboard
  public/Profile.jpg
  src/__test__/dashBoard/Seller.test.tsx
  src/__test__/dashBoard/SellerSlice.test.ts
  src/app/Dashboard/AllProductSlices.ts
  src/app/Dashboard/buyerSlice.ts
  src/app/store.ts
  src/components/dashBoard/DashboardSideNav.tsx
  src/index.css
  src/pages/Seller.tsx
  src/routes/AppRoutes.tsx
  tailwind.config.js
Labels: Front-End, Ready for TTL Review

#106 Fix the image on popular section on langing page
  src/components/Popular/Item.tsx
  src/components/dashBoard/Table.tsx
  vite.config.ts
Labels: Front-End, ready for review

#107 Add the best selling products table in admin dashboard
  package-lock.json
  src/__test__/dashBoard/bestSelling.test.tsx
  src/components/dashBoard/BestSellingProducts.tsx
  src/components/dashBoard/HomeDash.tsx
  src/features/Popular/bestSellingProductSlice.ts
  src/pages/SignUp.tsx
Labels: Ready for TTL Review, ready for review

#117 Added changes on footer
  package.json
  public/iconcart.svg
  src/components/Footer/Footer.tsx
Labels: bug, Ready for TTL Review

#116 Fix link to Product details page
  src/components/Popular/Item.tsx
Labels: Front-End, ready for review

#118 Feat contact page UI implementation #97
  .husky/pre-commit
  package-lock.json
  package.json
  src/__test__/contactForm.test.tsx
  src/__test__/faq.test.tsx
  src/app/store.ts
  src/assets/Degree of services (1).webp
  src/components/Contact/ContactForm.tsx
  src/components/Contact/FaqComponent.tsx
  src/components/Contact/FaqItem.tsx
  src/components/Contact/FaqList.tsx
  src/components/Orders/EditableOrder.tsx
  src/components/dashBoard/Table.tsx
  src/components/form/HSInput.tsx
  src/components/form/HSInputForm.tsx
  src/components/form/HSTextarea.tsx
  src/features/contact/contactSlice.ts
  src/pages/contact.tsx
  src/routes/AppRoutes.tsx
Labels: Front-End, Ready for TTL Review

#120 Fix: Product details
  .husky/pre-commit
  package-lock.json
  package.json
  src/__test__/home/ProductGridFour.test.tsx
  src/__test__/home/productCard.test.tsx
  src/__test__/home/productList.test.tsx
  src/__test__/wishlist.test.tsx
  src/components/Cart/Cart.tsx
  src/components/bannerAds/bannerSection.tsx
  src/components/home/ProductCard.tsx
  src/components/home/categories.tsx
  src/features/Products/ProductSlice.ts
  src/pages/Home.tsx
  src/pages/ProductDetails.tsx
  src/pages/Shop.tsx
  src/pages/Wishlist.tsx
Labels: Ready for TTL Review

#113 104 checkout page
  package.json
  public/icons/address.svg
  public/icons/card.svg
  public/icons/ccv.svg
  public/icons/date.svg
  public/icons/location.svg
  public/icons/user.svg
  public/momo.svg
  public/unionpay.svg
  src/__test__/Checkout/cardInput.test.tsx
  src/__test__/Checkout/checkout.test.tsx
  src/__test__/Orders/Orders.test.tsx
  src/__test__/navbar.test.tsx
  src/app/store.ts
  src/components/Cart/Cart.tsx
  src/components/Checkout/CardInput.tsx
  src/components/Checkout/Checkout.tsx
  src/components/Checkout/header.tsx
  src/components/Navbar.tsx
  src/components/Orders/OrderDetailsModal.tsx
  src/components/Orders/Orders.tsx
  src/components/dashBoard/DashboardSideNav.tsx
  src/features/Checkout/checkoutSlice.tsx
  src/features/Orders/ordersSlice.ts
  src/interfaces/checkout.ts
  src/interfaces/order.ts
  src/pages/Checkout.tsx
  src/routes/AppRoutes.tsx
  tsconfig.json
Labels: Ready for TTL Review, ready for review

#122 added About us Page
  public/doublequotes2.png
  public/doublequotesl.png
  public/whoweare.svg
  src/__test__/home/aboutus.test.tsx
  src/components/home/Aboutus.tsx
  src/routes/AppRoutes.tsx
Labels: Front-End, Ready for TTL Review

#109 Feat: implement coupons' functionaries
  .eslintrc.cjs
  package-lock.json
  package.json
  src/__test__/Coupons/CouponsFeature.test.ts
  src/__test__/dashBoard/dashBoardSideBar.test.tsx
  src/__test__/dashBoard/dashboardHome.test.tsx
  src/__test__/dashBoard/dashboardProductSlice.test.tsx
  src/app/store.ts
  src/components/TopCategories.tsx
  src/components/dashBoard/BestSellingProducts.tsx
  src/components/dashBoard/DashboardSideNav.tsx
  src/components/dashBoard/EditProduct.tsx
  src/components/dashBoard/HomeDash.tsx
  src/components/dashBoard/addProducts.tsx
  src/features/Coupons/CouponsFeature.ts
  src/features/SaleByCountry/SaleByCountrySlice.ts
  src/layout/DashbordLayout.tsx
  src/pages/AddCoupon.tsx
  src/pages/Coupons.tsx
  src/pages/EditCoupon.tsx
  src/pages/Seller.tsx
  src/pages/TwoFactorAuthForm.tsx
  src/routes/AppRoutes.tsx
  src/services/apiService
  vite.config.ts
Labels: Front-End, Ready for TTL Review

#114 Implement Role-Based Access Control
  .hintrc
  package-lock.json
  src/__test__/TableUserRole.test.tsx
  src/__test__/userRoleSlice.test.tsx
  src/app/store.ts
  src/assets/TableLogo.png
  src/components/dashBoard/DashboardSideNav.tsx
  src/components/dashBoard/UserRole.tsx
  src/features/userRole/userRoleSlice.tsx
  src/routes/AppRoutes.tsx
Labels: Front-End, ready for review

#133 Implement Customer Management
  src/components/dashBoard/DashboardSideNav.tsx
  src/pages/customer.tsx
  src/routes/AppRoutes.tsx
  vite.config.ts
Labels: Front-End, ready for review

#135 Fix cart, product and checkout
  package-lock.json
  src/__test__/Checkout/checkout.test.tsx
  src/__test__/home/productCard.test.tsx
  src/app/store.ts
  src/components/Cart/Cart.tsx
  src/components/Checkout/Checkout.tsx
  src/components/home/ProductCard.tsx
  src/components/home/categories.tsx
  src/features/Cart/cartSlice.tsx
  src/features/Checkout/checkoutSlice.tsx
  src/pages/ProductDetails.tsx
Labels: ready for review

#136 Added Category Dashboard
  package-lock.json
  src/__test__/dashBoard/Categories.test.tsx
  src/__test__/dashBoard/Seller.test.tsx
  src/components/dashBoard/Category.tsx
  src/components/dashBoard/DashboardSideNav.tsx
  src/pages/Seller.tsx
  src/routes/AppRoutes.tsx
Labels: Front-End, Ready for TTL Review

#132 Fix: Increase test coverage
  src/__test__/Cart/Cart.test.tsx
  src/__test__/productDetails.test.tsx
  src/__test__/shop.test.tsx
  src/components/salesMap/SalesMap.tsx
  src/features/Auth/SignInSlice.ts
  src/features/Orders/ordersSlice.ts
  src/pages/Coupons.tsx
  src/pages/ProductDetails.tsx
  src/pages/Shop.tsx
  src/routes/AppRoutes.tsx
  vite.config.ts
Labels: ready for review

#127 Feat: User is now able to perform payments
  package-lock.json
  package.json
  src/__test__/Cart/Cart.test.tsx
  src/assets/icons/add.svg
  src/assets/icons/discount.svg
  src/assets/icons/sports.svg
  src/components/Cart/Cart.tsx
  src/components/Cart/CartItem.tsx
  src/components/Checkout/Checkout.tsx
  src/features/Cart/cartSlice.tsx
  src/features/Checkout/checkoutSlice.ts
  vite.config.ts
Labels: Front-End, ready for review
